---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: stoped
