- name: Install nginx
  yum: name=nginx state=present
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/site.conf

- name: create directories for ssl certificates
  file: path=/etc/nginx/ssl state=directory

- name: copy TLS key
  copy: src=files/nginx.key dest=/etc/nginx/ssl/ owner=root mode=0600

- name: copy TLS certificate
  copy: src=files/nginx.crt dest=/etc/nginx/ssl/

- name: copy nginx config file site.conf
  copy: src=files/site.conf.j2 dest=/etc/nginx/conf.d/site.conf

- name: Copy nginx index.html
  template: src=templates/index.html dest=/usr/share/nginx/html

- name: http service state
  service: name=nginx state=started enabled=yes
  notify:
    - nginx systemd
